channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.5
  - torchvision
  - Pygments=2.3.1 
  - setuptools=41.0.1 
  - mock=1.0.1 
  - pillow=5.4.1 
  - alabaster>=0.7,<0.8,!=0.7.5
  - commonmark=0.8.1
  - recommonmark=0.5.0 
  - sphinx<2 
  - pip
  - pip:
      - sphinx-rtd-theme<0.5 
      - readthedocs-sphinx-ext<1.1
